name: Build and Deploy (Android APK + iOS Simulator Zip) to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK (no signing)
        run: flutter build apk --debug

      - name: Upload Android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  build_ios:
    name: Build iOS Simulator .app zip
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode Version
        run: xcodebuild -version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build iOS simulator app (no code signing)
        run: flutter build ios --simulator --debug

      - name: Zip simulator app
        run: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build/ios/iphonesimulator/Runner.app.zip

  deploy_pages:
    name: Deploy to GitHub Pages
    needs: [build_android, build_ios]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Prepare site dir
        run: |
          mkdir -p site

      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: site

      - name: Download iOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-simulator-app
          path: site

      - name: Generate index.html
        run: |
          cat > site/index.html << 'HTML'
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <title>Pinitu Downloads</title>
              <style>
                body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; padding: 24px; line-height: 1.5; }
                .card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 16px; max-width: 640px; }
                h1 { margin-top: 0; }
                a.button { display: inline-block; padding: 10px 16px; background: #ef4444; color: #fff; border-radius: 8px; text-decoration: none; }
                .muted { color: #6b7280; font-size: 14px; }
              </style>
            </head>
            <body>
              <h1>Pinitu CI Downloads</h1>
              <div class="card">
                <h2>Android</h2>
                <p class="muted">Debug APK (install via adb or drag onto emulator)</p>
                <p><a class="button" href="./app-debug.apk">Download app-debug.apk</a></p>
                <hr />
                <h2>iOS</h2>
                <p class="muted">Simulator build (Runner.app.zip). Unzip and install with Xcode/Simulator.</p>
                <p><a class="button" href="./Runner.app.zip">Download Runner.app.zip</a></p>
              </div>
            </body>
          </html>
          HTML

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
